### PR TITLE
Add arguments type in suggestions

### PR DESCRIPTION
**Pull request by hammeron-art**
Added arguments type to the completation hint.

This shows simple types, function signatures and generics:
sample

### CODE REVIEW

**Comment by hammeron-art** [comment]
Right, it was already implemented but not being used. At least it wasn't working on Windows.
Suggestions with list now parse types.

**Comment by jeremyfa** [comment]
Ideally, this should be configurable in the plugin settings. I personally prefer to hide the types in the list in order to see more arguments, especially because I can see the type hints when typing inside the signature after.

Also note that this part of the code is currently being refactored, and the suggestions lists will change in the future to leverage latest atom autocomplete features. So not sure it is the right moment to add features on this part, unless @underscorediscovery is ok with it.

**Comment by hammeron-art** [comment]
Not sure what you mean by typing inside the signature.
Ins't there a bug in the autocomplete-plus that hides the hint when typing arguments?
On my side the code hint doens't work like this gif https://camo.githubusercontent.com/547b7b8b0c45a47c4f95f72b7bb38b90a3d682a8/687474703a2f2f692e696d6775722e636f6d2f4f7a4e323569692e676966

**Comment by jeremyfa** [comment]
Heh, actually the feature is not working anymore. Something must be broken since the last autocomplete-plus plugin. I will look into it...

Anyway, the current way of handling type hints (like the gif animation) is temporary. Eventually autocomplete-plus should be only used for _regular_ code completion, while type hints should be handled separately. This would at the same time solve the problem of having no type hint right after `(` character.

**Pull request closed without merging**
