### PR TITLE
fixes tree view problem on newer versions of atom

### PR DESCRIPTION
**Pull request by sercant**
Fixes issue #68

### CODE REVIEW

**Comment by ruby0x1** [comment]
Thanks! I'll test and upstream soon

**Comment by sercant** [comment]
Needs to be tested with an old version of atom to see if it's compatible.

**Comment by ruby0x1** [comment]
yep!

**Comment by ruby0x1** [comment]
there was this one as well that I was in the process of getting to test https://github.com/snowkit/atom-flow/pull/18

**Comment by sercant** [comment]
Perfect! Hope either one of the solution fixes the issue.

**Pull request merged**
